### ISSUE TITLE
Have linked citations in pdf

### ISSUE THREAD

**Issue by garyee** [zotero/zotero-google-docs-integration#43]
Hi,

I was very pleased when I discovered that there is a Google Docs connector for Zotero. I wrote my document and wanted to download the pdf to see how it looks, because I have to submit a .pdf file.
I was kind of expecting the citations to be linked to the bibiography in the pdf file, then I saw the pop-up...
If there is some kind of hook, that let's you intercept a "download as pdf" action, could you not just use that hook to change the citations to bookmarks or something like that?
This would be great!

**Comment by adomasven** [comment]
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.

We're unable to link citations to bibliography due to technical reasons. We do intercept the download action, but only to notify the user to unlink the citations, since that action takes a significant amount of time and a copy of the document needs to be created (something which we also cannot automatize).

**Comment by garyee** [comment]
You should disclose this to the users then. If I had known beforehand I would not have used the google-docs plugin, as there are a good zotero integrations with other office software.

**Comment by adomasven** [comment]
No Zotero word processor integrations link citations to bibliography. Google Docs, Word and LibreOffice Zotero integrations are feature equal.

**Comment by garyee** [comment]
Oh okay I did not know that. That is unfortunate, thank you.
